class Category:
    def __init__(self, id, name, products):
        self.id = id
        self.name = name
        self.products = products  


class Product:
    def __init__(self, name, description, price):
        self.name = name
        self.description = description
        self.price = price


all_products = [
    Product("Ace Instant Porridge 1kg Assorted", "Instant porridge mix", 27.99),
    Product("All Gold Tomato Sauce 700g", "Tomato sauce", 44.99),
    Product("Aromat Original 50g", "Seasoning", 24.99),
    Product("Bakers Inn Bread", "Brown loaf bread", 23.99),
    Product("Bakers Inn White Loaf", "White loaf bread", 23.99),
    Product("Bella Macaroni 3kg", "Macaroni pasta", 82.99),
    Product("Bisto Gravy 125g", "Gravy mix", 19.99),
    Product("Blue Band Margarine 500g", "Margarine", 44.99),
    Product("Blue Ribbon Self Raising 2kg", "Self-raising flour", 37.99),
    Product("Bokomo Cornflakes 1kg", "Cornflakes", 54.90),
    Product("Bullbrand Corned Beef 300g", "Corned beef", 39.99),
    Product("Buttercup Margarine 500g", "Margarine", 44.99),
    Product("Cashel Valley Baked Beans 400g", "Baked beans", 18.99),
    Product("Cerevita 500g", "Cereal", 69.99),
    Product("Cookmore Cooking Oil 2L", "Cooking oil", 67.99),
    Product("Cross and Blackwell Mayonnaise 700g", "Mayonnaise", 49.99),
    Product("Dried Kapenta 1kg", "Dried fish", 134.99),
    Product("Ekonol Rice 5kg", "Rice", 119.29),
    Product("Fattis Macaroni 500g", "Macaroni", 22.99),
    Product("Gloria Self Raising Flour 5kg", "Self-raising flour", 79.90),
    Product("Jungle Oats 1kg", "Oats", 44.99),
    Product("Knorr Brown Onion Soup 50g", "Onion soup mix", 7.99),
    Product("Lucky Star Pilchards in Tomato Sauce 155g", "Pilchards", 17.99),
    Product("Mahatma Rice 2kg", "Rice", 52.99),
    Product("Peanut Butter 350ml", "Peanut butter", 19.99),
    Product("Roller Meal 10kg- Zim Meal", "Maize meal", 136.99),
    Product("Stella Teabags 100 Pack", "Tea bags", 42.99),
    Product("Mazoe Raspberry 2 Litres", "Fruit drink", 67.99),
    Product("Cremora Creamer 750g", "Coffee creamer", 72.99),
    Product("Everyday Milk Powder 400g", "Milk powder", 67.99),
    Product("Freshpack Rooibos 80s", "Rooibos tea", 84.99),
    Product("Nestle Gold Cross Condensed Milk 385g", "Condensed milk", 29.99),
    Product("Pine Nut Soft Drink 2L", "Soft drink", 37.99),
    Product("Mazoe Blackberry 2L", "Fruit drink", 68.99),
    Product("Quench Mango 2L", "Fruit drink", 32.99),
    Product("Coca Cola 2L", "Soft drink", 39.99),
    Product("Pfuko Dairibord Maheu 500ml", "Maheu drink", 14.99),
    Product("Sprite 2 Litres", "Soft drink", 37.99),
    Product("Pepsi (500ml x 24)", "Soft drink pack", 178.99),
    Product("Probands Milk 500ml", "Steri milk", 20.99),
    Product("Lyons Hot Chocolate 125g", "Hot chocolate", 42.99),
    Product("Dendairy Long Life Full Cream Milk 1 Litre", "Long life milk", 28.99),
    Product("Joko Tea Bags 100", "Tea bags", 55.99),
    Product("Cool Splash 5 Litre Orange Juice", "Orange juice", 99.99),
    Product("Cremora Coffee Creamer 750g", "Coffee creamer", 72.99),
    Product("Fanta Orange 2 Litres", "Soft drink", 37.99),
    Product("Quench Mango 5L", "Fruit drink", 92.25),
    Product("Ricoffy Coffee 250g", "Coffee", 52.99),
    Product("Dendairy Low Fat Long Life Milk", "Low fat milk", 28.99),
    Product("Quickbrew Teabags 50", "Teabags", 25.99),
    Product("Fruitrade 2L Orange Juice", "Orange juice", 32.90),
    Product("Mazoe Orange Crush 2L", "Fruit drink", 69.99),
    Product("Joko Rooibos Tea Bags 80s", "Rooibos tea", 84.99),
    Product("Sta Soft Lavender 2L", "Fabric softener", 59.99),
    Product("Sunlight Dishwashing Liquid 750ml", "Dishwashing liquid", 35.99),
    Product("Nova 2-Ply Toilet Paper 9s", "Toilet paper", 49.90),
    Product("Domestos Thick Bleach Assorted 750ml", "Bleach cleaner", 39.99),
    Product("Doom Odourless Multi-Insect Killer 300ml", "Insect killer", 32.90),
    Product("Handy Andy Assorted 500ml", "Multi-surface cleaner", 32.99),
    Product("Jik Assorted 750ml", "Disinfectant", 29.99),
    Product("Maq Dishwashing Liquid 750ml", "Dishwashing liquid", 35.99),
    Product("Maq 3kg Washing Powder", "Washing powder", 72.90),
    Product("Maq Handwashing Powder 2kg", "Handwashing powder", 78.99),
    Product("Elangeni Washing Bar 1kg", "Washing bar", 24.59),
    Product("Vim Scourer 500g", "Scouring pad", 21.99),
    Product("Matches Carton (10s)", "Matches", 8.99),
    Product("Surf 5kg", "Washing powder", 159.99),
    Product("Britelite Candles 6s", "Candles", 32.99),
    Product("Sta-Soft Assorted Refill Sachet 2L", "Fabric softener refill", 39.99),
    Product("Poppin Fresh Dishwashing Liquid 750ml", "Dishwashing liquid", 22.99),
    Product("Poppin Fresh Toilet Cleaner 500ml", "Toilet cleaner", 34.99),
    Product("Poppin Fresh Multi-Purpose Cleaner", "Multi-purpose cleaner", 25.99),
    Product("Softex Toilet Tissue 1-Ply 4s", "Toilet tissue", 39.99),
    Product("Protex Bath Soap Assorted 150g", "Bath soap", 21.99),
    Product("Sona Bath Soap 300g", "Bath soap", 13.99),
    Product("Kiwi Black Shoe Polish 50ml", "Shoe polish", 18.99),
    Product("Nivea Women's Roll On Assorted 50ml", "Deodorant", 33.99),
    Product("Clere Lanolin Lotion 400ml", "Body lotion", 35.99),
    Product("Vaseline Men Petroleum Jelly 250ml", "Petroleum jelly", 9.99),
    Product("Vaseline Petroleum Jelly Original 250ml", "Petroleum jelly", 39.99),
    Product("Sunlight Bath Soap Lively Lemon 175g", "Bath soap", 10.90),
    Product("Shield Fresh Shower Deo", "Deodorant", 24.99),
    Product("Hoity Toity Ladies Spray", "Ladies spray", 22.90),
    Product("Brut Total Attraction Roll On", "Deodorant", 17.90),
    Product("Vaseline Men Lotion 400ml", "Body lotion", 64.99),
    Product("Shield Dry Musk Roll On 50ml", "Deodorant", 24.99),
    Product("Sunlight Bath Soap Juicy Orange 150g", "Bath soap", 10.99),
    Product("Axe Men Roll On Wild Spice", "Deodorant", 32.99),
    Product("Nivea Rich Nourishing Cream 400ml", "Body cream", 79.99),
    Product("Dawn Rich Lanolin Lotion 400ml", "Body lotion", 24.90),
    Product("Twinsaver 2-Ply Toilet Paper", "Toilet paper", 32.90),
    Product("Hoity Toity Body Lotion 400ml", "Body lotion", 44.90),
    Product("Axe Deo Assorted Men", "Deodorant", 36.99),
    Product("Stayfree Pads Scented Wings 10s", "Sanitary pads", 15.99),
    Product("Geisha Bath Soap", "Bath soap", 9.90),
    Product("Clere Berries and Cream 500ml", "Body lotion", 39.99),
    Product("Clere Body Cream Cocoa Butter 500ml", "Body cream", 39.99),
    Product("Ingram's Camphor Cream Herbal 500ml", "Herbal cream", 57.99),
    Product("Lifebuoy Lemon Fresh 175g", "Bath soap", 16.99),
    Product("Aquafresh Fresh and Minty Toothpaste 100ml", "Toothpaste", 22.99),
    Product("Lil Lets Pads Super Maxi Thick 8s", "Sanitary pads", 13.99),
    Product("Nivea Men Lotion (Assorted) 400ml", "Body lotion", 79.99),
    Product("Nivea Men Cream (Assorted) 400ml", "Body cream", 79.99),
    Product("Nivea Body Creme Deep Impact 400ml", "Body cream", 79.99),
    Product("Clere Berries and Creme Lotion 400ml", "Body lotion", 35.99),
    Product("Clere Men 400ml Lotion Assorted", "Men's lotion", 35.99),
    Product("Pearl/Sona Bath Soap Assorted 200g", "Bath soap", 13.99),
    Product("Nivea Intensive Moisturizing Creme 500ml", "Moisturizing cream", 79.99),
    Product("Protex for Men Assorted Bath Soap 150g", "Bath soap", 21.99),
    Product("Axe Roll On Assorted", "Deodorant", 36.99),
    Product("Satiskin Floral Bouquet 2L", "Body wash", 99.99),
    Product("Nivea Deep Impact Lotion 400ml", "Body lotion", 79.99),
    Product("Nivea Ladies Deo Pearl Beauty", "Deodorant", 32.90),
    Product("Nivea Rich Nourishing Lotion 400ml", "Body lotion", 79.99),
    Product("Nivea Deo Dry Confidence Women 150ml", "Deodorant", 32.99),
    Product("Dove Roll On Assorted", "Deodorant", 26.99),
    Product("Satiskin Foam Bath Berry Fantasy 2L", "Foam bath", 99.99),
    Product("Clere Glycerin 100ml", "Glycerin", 21.99),
    Product("Nivea Body Creme Max Hydration 400ml", "Body cream", 79.99),
    Product("Clere Men Body Cream Assorted 400ml", "Men's body cream", 39.99),
    Product("Nivea Intensive Moisturizing Lotion 400g", "Moisturizing lotion", 79.99),
    Product("Lux Soft Touch 175g", "Bath soap", 21.99),
    Product("Lifebuoy Total 10 175g", "Bath soap", 16.99),
    Product("Jade Bath Soap Assorted", "Bath soap", 12.60),
    Product("Stayfree Pads Unscented Wings 10s", "Sanitary pads", 19.90),
    Product("Colgate 100ml", "Toothpaste", 18.99),
    Product("Clere Men Fire 450ml", "Men's lotion", 39.99),
    Product("Shield Men's Roll On Assorted", "Deodorant", 24.99),
    Product("Shower to Shower Ladies Deodorant", "Deodorant", 27.99),
    Product("Lux Soft Caress 175g", "Bath soap", 21.99),
    Product("Nivea Men Revitalizing Body Cream 400g", "Body cream", 79.99),
    Product("Clere Cocoa Butter Lotion 400ml", "Body lotion", 32.99),
    Product("Shield Women's Roll On Assorted", "Deodorant", 24.99),
    Product("Nivea All Season Body Lotion 400ml", "Body lotion", 79.99),
    Product("Nivea Men Roll On Assorted 50ml", "Deodorant", 33.99),
    Product("Protex Deep Clean Bath Soap 150g", "Bath soap", 21.99),
    Product("Sunlight Cooling Mint Bathing Soap 150g", "Bath soap", 10.99),
    Product("Dettol 250ml", "Antiseptic liquid", 25.99),
    Product("Woods Peppermint 100ml", "Body spray", 46.90),
    Product("Med Lemon Sachet 6.1g", "Lemon sachet", 7.90),
    Product("Predo Adult Diapers 30s (M/L/XL)", "Adult diapers", 317.99),
    Product("Ingram's Camphor Moisture Plus 500ml", "Moisturizing cream", 59.99),
    Product("Disposable Face Mask 50s", "Face masks", 39.99),
    Product("Jena Maputi 15pack", "Popcorn", 23.99),
Product("Tiggies Assorted 50s", "Snacks", 74.99),
Product("L Choice Assorted Biscuits", "Biscuits", 12.90),
Product("Sneaker Nax Bale Pack 2kg", "Snacks", 39.90),
Product("Yogueta Lollipop Split Pack 48 Pack", "Lollipops", 59.99),
Product("Arenel Choice Assorted Biscuits 150g", "Biscuits", 19.90),
Product("Willards Things 150g", "Cheese snacks", 14.99),
Product("Stumbo Assorted Lollipops 48s", "Lollipops", 59.99),
Product("Pringles Original 110g", "Potato chips", 22.90),
Product("Nibble Naks 20pack", "Snacks", 29.99),
Product("King Kurls Chicken Flavour 100g", "Snacks", 12.90),
Product("Nik Naks 50s Pack Assorted", "Snacks", 54.90),
Product("Proton Ramba Waraira Cookies 1 kg", "Cookies", 68.99),
Product("Lobels Marie Biscuits", "Biscuits", 6.90),
Product("Chocolate Coated Biscuits", "Chocolate biscuits", 35.99),
Product("Top 10 Assorted Sweets", "Assorted sweets", 9.90),
Product("Jelido Magic Rings 102 Pieces", "Candy rings", 48.90),
Product("Lays Assorted Flavours 105g", "Potato chips", 52.99),
Product("Charhons Biscuits 2kg", "Biscuits", 99.99),
Product("Zap Nax Cheese and Onion 100g", "Snacks", 3.99),
Product("Economy Steak on Bone Beef Cuts 1kg", "Fresh beef", 147.99),
Product("Parmalat Cheddar Cheese", "Cheddar cheese slices", 89.99),
Product("Colcom Beef Polony 3kg", "Beef polony", 299.00),
Product("Colcom Tastee French Polony 750g", "French polony", 116.99),
Product("Colcom Chicken Polony 3kg", "Chicken polony", 219.90),
Product("Bulk Mixed Pork 1kg", "Mixed pork", 128.99),
Product("Potatoes 7.5kg (Small Pocket)", "Fresh potatoes", 219.99),
Product("Colcom Tastee Chicken Polony 1kg", "Chicken polony", 34.90),
Product("Colcom Garlic Polony 3kg", "Garlic polony", 220.00),
Product("Colcom Tastee Beef Polony 1kg", "Beef polony", 35.00),
Product("Wrapped Mixed Size Fresh Eggs 30", "Fresh eggs", 149.99),
Product("Texas Meats Juicy Boerewors", "Boerewors", 159.99),
Product("Unwrapped Small Size Fresh Eggs 30s", "Fresh eggs", 99.99),
Product("Irvines Mixed Chicken Cuts 2kg", "Mixed chicken cuts", 179.99),
Product("Dairibord Yoghurt 150ml", "Yoghurt", 15.99),
Product("Plastic Cover 3 Meter Roll", "Plastic cover", 7.99),
Product("Ruler 30cm", "Ruler", 6.99),
Product("A4 Bond Paper White", "Bond paper", 126.99),
Product("Kakhi Cover 3 Meter Roll", "Kakhi cover", 8.99),
Product("School Trunk", "School trunk", 750.00),
Product("Oxford Maths Set", "Maths set", 34.99),
Product("Grade 1-3 Exercise Book A4 32 Page (10 Pack)", "Exercise books", 36.99),
Product("72 Page Newsprint Maths Book (10 Pack)", "Maths books", 69.99),
Product("Cellotape Large 40yard", "Cellotape", 5.99),
Product("Newsprint 2 Quire Counter Books (192 Page)", "Counter books", 28.99),
Product("72 Page Newsprint Writing Exercise Book (10 Pack)", "Writing exercise books", 69.99),
Product("Cellotape Small 20yard", "Cellotape", 3.99),
Product("Eversharp Pens Set x 4", "Pens set", 14.99),
Product("Newsprint 1 Quire (96 Page) Counter Book", "Counter book", 17.99),
Product("HB Pencils x 12 Set", "Pencils set", 24.99),
Product("Sharp Scientific Calculator", "Scientific calculator", 319.99),
Product("32 Page Newsprint Plain Exercise Book (10 Pack)", "Plain exercise books", 36.99),
Product("Huggies Dry Comfort Jumbo Size 5 (44s)", "Diapers", 299.99),
Product("Pampers Fresh Clean Wipes 64 Pack", "Baby wipes", 31.90),
Product("Johnson and Johnson Scented Baby Jelly 325ml", "Baby jelly", 52.99),
Product("Vaseline Baby Jelly 250g", "Baby jelly", 31.90),
Product("Predo Baby Wipes Assorted 120s", "Baby wipes", 52.90),
Product("Huggies Dry Comfort Size 3 Jumbo (76)", "Diapers", 299.99),
Product("Huggies Dry Comfort Size 2 Jumbo (94)", "Diapers", 299.99),
Product("Huggies Dry Comfort Size 4 Jumbo", "Diapers", 299.99),
Product("Bennetts Aqueous Cream 500ml", "Aqueous cream", 39.30),
Product("Predo Baby Wipes Assorted 80s", "Baby wipes", 38.99),
Product("Crez Babyline Petroleum Jelly 500g", "Petroleum jelly", 42.99),
Product("Johnson and Johnson Lightly Fragranced Aqueous Cream 350ml", "Aqueous cream", 39.90),
Product("Nestle Baby Cereal with Milk Regular Wheat 250g", "Baby cereal", 34.99),
Product("Nan 2: Infant Formula Optipro 400g", "Infant formula", 79.99),
Product("Nan 1: Infant Formula Optipro 400g", "Infant formula", 79.99),
]


def list_all_products():
    order_system = OrderSystem()
    products = order_system.get_all_products()
    
    product_lines = []
    for i, product in enumerate(products):
        product_lines.append(f"{i + 1}. {product.name} - ${product.price}")
    
    return "\n".join(product_lines)
